### ISSUE TITLE
Prototipo de Realidad Aumentada.

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/actividad-3-prototipo-de-realidad-aumentada-remi-team-1#1]
![image](https://user-images.githubusercontent.com/46431649/221277605-666e2feb-348f-4279-b78c-553b792fdfbb.png)

_Ilustración 1. Prototipo de la aplicación pensada por el equipo REMI._

**Comment by Ferch0419** [comment]
Calificación: 20/20

**Comment by josealfredo79** [comment]
bien hecho
